name: Run-Daily

on:
  workflow_dispatch:
  schedule:
  # Run at 00:15 UTC+3
    - cron: '15 3 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
    - run: rustup update stable && rustup default stable
    - name: Build release
      run: cargo build --release
    - name: Hello world
      run: |
        echo "Hello world"