name: Run-Daily

on:
  workflow_dispatch:
  schedule:
  # Run at 00:15 UTC+3
    - cron: '15 3 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 
    - run: rustup update stable && rustup default stable
    - name: Build release
      run: cargo build --release
    - name: Run sanalouhos
      run: cargo run --release 1000 > results.txt
    - name: Print response
      run: cat results.txt
    - name: Build website
      run: | 
        cat results.txt | grep "##.*##" | awk -F'##' '{print $2}' | sort | uniq -c | sort -nr | awk '{print $2 "," $1}' | paste -sd ';' - > counts.txt
        sed -e "s/\${word_list}/$(cat counts.txt)/" page_template.html > index.html
    - name: Echo website html
      run: cat index.html
